image: golang:1.11.4

before_script:
  - export DOCKER_REPOSITORY="mendersoftware/mender-stress-test-client"
  - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
  - export SERVICE_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG
  - export COMMIT_TAG="$CI_COMMIT_REF_SLUG"_"$CI_COMMIT_SHA"

stages:
  - test
  - build
  - publish

test:format:
  stage: test
  before_script:
    - mkdir -p /go/src/github.com/mendersoftware
    - cp -r $CI_PROJECT_DIR /go/src/github.com/mendersoftware/mender-stress-test-client
    - cd /go/src/github.com/mendersoftware/mender-stress-test-client
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  image: docker
  services:
    - docker:dind
  stage: build
  script:
    - echo "building mender-stress-test-client for ${SERVICE_IMAGE}"
    - docker build -t $SERVICE_IMAGE .
    - docker save $SERVICE_IMAGE > image.tar
  artifacts:
    paths:
      - image.tar

publish:binary:
  stage: publish
  dependencies:
    - compile
  script:
    - echo "publish mender-stress-test-client binary to s3 here"